import json
import logging
import re
import time
from pathlib import Path
from typing import Any

from groq import Groq

from .sanity_check import (
    check_estructura_minima,
    check_texto,
)

logger = logging.getLogger("uns.llm")

PROMPT_VERSION = "v2"
MODEL_DEFAULT = "llama-3.3-70b-versatile"
MAX_CHARS_PER_CHUNK = 3_500

# Secciones primarias: cada año y el bloque de optativas
_SECCION_RE = re.compile(
    r"^(PRIMER\s+AÑO|SEGUNDO\s+AÑO|TERCER\s+AÑO|CUARTO\s+AÑO|QUINTO\s+AÑO"
    r"|SEXTO\s+AÑO|SEPTIMO\s+AÑO|MATERIAS?\s+OPTATIVAS?)",
    re.IGNORECASE | re.MULTILINE,
)
# Subsecciones: cuatrimestres y agrupadores de optativas
_SUBSECCION_RE = re.compile(
    r"^(Primer\s+Cuatrimestre|Segundo\s+Cuatrimestre|G\d{4}\s)",
    re.IGNORECASE | re.MULTILINE,
)

SYSTEM_PROMPT = """\
You are a deterministic data normalization engine for academic curricula.

Your task is to transform raw, unstructured academic plan content into a strictly valid JSON object that follows the PlanData schema.

---

## INPUT

You will receive:

1. RAW_TEXT:
   Unstructured text extracted from a PDF (may contain noise, broken formatting, OCR issues).

2. OPTIONAL_BASE_JSON (optional):
   A partially completed JSON generated by a regex parser. Some fields may be null or incorrect.

3. ALLOW_OVERWRITE (boolean):

* If true → you MAY modify existing values in OPTIONAL_BASE_JSON (only if clearly incorrect)
* If false → you MUST NOT modify any existing non-null value

---

## OUTPUT (STRICT)

Return ONLY a valid JSON object.

* No explanations
* No comments
* No markdown
* No extra text

---

## TARGET SCHEMA (PlanData)

```json
{
  "plan": {
    "carrera": "string | null",
    "universidad": "string | null",
    "codigo_plan": "string | null"
  },
  "materias": [
    {
      "id": "string | null",
      "nombre": "string | null",
      "año": "string | null",
      "cuatrimestre": "string | null",
      "horas": "string | null",
      "tipo": "materia | null",
      "categoria": "normal | optativa | null",
      "grupo_opcion": "string (ID of agrupador) | null",
      "subtipo": "string | null",
      "correlativas": {
        "<id_materia>": {
          "para_cursar": "cursada | aprobada | null",
          "para_rendir": "cursada | aprobada | null"
        }
      },
      "requisito_especial": {
        "tipo": "minimo_materias_aprobadas | prueba_idioma | null",
        "cantidad": "number | null",
        "descripcion": "string | null"
      }
    }
  ],
  "agrupadores": [
    {
      "id": "string",
      "nombre": "string | null",
      "tipo": "optativa_grupo | idioma | null",
      "opciones": ["string (IDs of materias)"],
      "año": "string | null",
      "cuatrimestre": "string | null"
    }
  ]
}
```

### Field details

**plan**
- `carrera`: name of the degree (e.g. "Abogacia", "Ingeniería en Sistemas")
- `universidad`: university name (e.g. "Universidad Nacional del Sur")
- `codigo_plan`: plan code/version (e.g. "Plan 2020 - Versión 2")

**materias[].correlativas**
- Object keyed by the prerequisite subject ID (string)
- `para_cursar`: requirement to enroll — "cursada" (passed) or "aprobada" (approved/final exam passed)
- `para_rendir`: requirement to take the final exam — same values
- If a requirement does not apply → null
- If no prerequisites → empty object {}

**materias[].categoria**
- `"normal"` for mandatory subjects
- `"optativa"` for elective subjects that belong to an agrupador

**materias[].grupo_opcion**
- The ID of the agrupador this elective belongs to (e.g. "G2347")
- null for mandatory subjects

**materias[].requisito_especial**
- Only present when there is a special enrollment/completion condition beyond regular correlativas
- `tipo: "minimo_materias_aprobadas"` → student must have approved at least `cantidad` subjects
- `tipo: "prueba_idioma"` → student must pass a language proficiency test
- Omit the field entirely if no special requirement exists

**agrupadores**
- Each agrupador groups elective options a student must choose from
- `tipo: "optativa_grupo"` for elective subject groups
- `tipo: "idioma"` for language exam groups
- `opciones`: list of materia IDs that are options within this group

---

## OPERATING MODES

### Mode A — Full extraction (no OPTIONAL_BASE_JSON provided)

* Extract all data from RAW_TEXT

### Mode B — Refinement (OPTIONAL_BASE_JSON provided)

* Fill ONLY missing fields (null or empty)
* Respect existing structure
* Apply overwrite rules (see below)

---

## CRITICAL RULE: NO OVERWRITE

If OPTIONAL_BASE_JSON is provided:

* You MUST NOT replace, modify, or delete any existing non-null value
* UNLESS ALLOW_OVERWRITE = true

If ALLOW_OVERWRITE = false:

* Existing values are considered authoritative
* You can ONLY fill null/empty fields

If ALLOW_OVERWRITE = true:

* You MAY correct values ONLY if they are clearly incorrect based on RAW_TEXT
* DO NOT make speculative changes

---

## CRITICAL RULES (MUST FOLLOW)

1. NEVER invent or infer data — if not explicitly present → use null

2. Extract ALL subjects including electives (optativas). Do not skip sections.

3. Correlativas:
   * Extract only explicit references from RAW_TEXT
   * Distinguish para_cursar vs para_rendir when the text makes it clear
   * If the type is not distinguishable → use the same value for both
   * If unreadable → null

4. IDs must be strings, exact format. If corrupted → null.

5. año: normalize to "Primer Año", "Segundo Año", "Tercer Año", "Cuarto Año", "Quinto Año", etc.

6. cuatrimestre: normalize to "Primer Cuatrimestre" or "Segundo Cuatrimestre". If annual → null.

7. Each subject must be a separate object. Do NOT merge subjects.

8. For each agrupador detected, list ALL its member subject IDs in `opciones`.

9. Set `categoria: "optativa"` and `grupo_opcion: <agrupador_id>` for every elective subject.

---

## ERROR HANDLING

* Missing → null
* Ambiguous → null
* Conflicting (OPTIONAL_BASE_JSON present, ALLOW_OVERWRITE false) → keep existing value

---

## VALIDATION CONSTRAINTS

* "materias" must be non-empty if any subjects are detected
* Each materia must have at least one non-null field (id or nombre)
* "correlativas" must always be an object (never null or array)
* "agrupadores" must always be an array (empty [] if none detected)

---

## FINAL INSTRUCTION

Your response MUST be strict JSON, schema-compliant, deterministic, and safe for automatic validation.

If unsure → use null.
"""


class LLMParseError(ValueError):
    pass


def _construir_user_message(
    texto_limpio: str,
    base_json: dict | None,
    allow_overwrite: bool,
) -> str:
    partes = [f"RAW_TEXT:\n{texto_limpio}"]

    if base_json is not None:
        partes.append(
            "OPTIONAL_BASE_JSON:\n" + json.dumps(base_json, ensure_ascii=False, indent=2)
        )
    else:
        partes.append("OPTIONAL_BASE_JSON:\nnone")

    partes.append(f"ALLOW_OVERWRITE: {'true' if allow_overwrite else 'false'}")

    return "\n\n".join(partes)


def _extraer_json(texto: str) -> Any:
    # 1. JSON directo
    try:
        return json.loads(texto)
    except json.JSONDecodeError:
        pass

    # 2. Bloque ```json ... ```
    match = re.search(r"```json\s*([\s\S]+?)\s*```", texto, re.IGNORECASE)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass

    # 3. Primer { hasta último }
    start = texto.find("{")
    end = texto.rfind("}")
    if start != -1 and end != -1 and end > start:
        try:
            return json.loads(texto[start : end + 1])
        except json.JSONDecodeError:
            pass

    raise LLMParseError(
        f"No se pudo parsear el JSON del LLM. Respuesta recibida ({len(texto)} chars):\n{texto[:500]}"
    )


def _guardar_traza(trace_dir: Path, nombre: str, contenido: str) -> None:
    try:
        trace_dir.mkdir(parents=True, exist_ok=True)
        (trace_dir / nombre).write_text(contenido, encoding="utf-8")
    except Exception as exc:
        logger.warning("No se pudo escribir traza %s: %s", nombre, exc)


def _cortar_por_patron(texto: str, patron: re.Pattern) -> list[str]:
    """Devuelve una lista con header + cada sección como elemento separado."""
    matches = list(patron.finditer(texto))
    if not matches:
        return [texto]
    boundaries = [m.start() for m in matches] + [len(texto)]
    secciones = []
    header = texto[: boundaries[0]]
    if header.strip():
        secciones.append(header)
    for i in range(len(boundaries) - 1):
        s = texto[boundaries[i] : boundaries[i + 1]]
        if s.strip():
            secciones.append(s)
    return secciones


def _fusionar_pequenos(secciones: list[str]) -> list[str]:
    """Fusiona secciones consecutivas mientras la suma no supere el límite."""
    chunks: list[str] = []
    actual = ""
    for s in secciones:
        if len(actual) + len(s) <= MAX_CHARS_PER_CHUNK:
            actual += s
        else:
            if actual.strip():
                chunks.append(actual)
            actual = s
    if actual.strip():
        chunks.append(actual)
    return chunks


def _partir_en_chunks(texto: str) -> list[str]:
    """Divide por año, subdivide bloques grandes por cuatrimestre/agrupador, luego fusiona pequeños."""
    secciones: list[str] = []
    for seccion in _cortar_por_patron(texto, _SECCION_RE):
        if len(seccion) > MAX_CHARS_PER_CHUNK:
            secciones.extend(_cortar_por_patron(seccion, _SUBSECCION_RE))
        else:
            secciones.append(seccion)
    return _fusionar_pequenos(secciones)


def _llamar_llm(client: Groq, model_name: str, user_message: str) -> str:
    response = client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
        temperature=0,
        response_format={"type": "json_object"},
    )
    return response.choices[0].message.content


def _mergear_resultados(parciales: list[dict]) -> dict[str, Any]:
    """Combina múltiples PlanData parciales en uno. El plan lo toma del primero que lo tenga."""
    plan: dict = {}
    materias: list = []
    agrupadores: list = []
    ids_vistos: set = set()
    agr_ids_vistos: set = set()

    for resultado in parciales:
        if not plan:
            plan = resultado.get("plan") or {}
        for m in resultado.get("materias") or []:
            mid = m.get("id") if isinstance(m, dict) else None
            if mid and mid in ids_vistos:
                continue
            if mid:
                ids_vistos.add(mid)
            materias.append(m)
        for agr in resultado.get("agrupadores") or []:
            aid = agr.get("id") if isinstance(agr, dict) else None
            if aid and aid in agr_ids_vistos:
                continue
            if aid:
                agr_ids_vistos.add(aid)
            agrupadores.append(agr)

    return {"plan": plan, "materias": materias, "agrupadores": agrupadores}


def normalizar(
    texto_limpio: str,
    *,
    base_json: dict | None = None,
    allow_overwrite: bool = False,
    model_name: str = MODEL_DEFAULT,
    trace_dir: Path | None = None,
) -> dict[str, Any]:
    check_texto(texto_limpio)

    if trace_dir:
        _guardar_traza(trace_dir, "02_texto_limpio.txt", texto_limpio)
        if base_json is not None:
            _guardar_traza(
                trace_dir,
                "04_base_plandata.json",
                json.dumps(base_json, ensure_ascii=False, indent=2),
            )

    chunks = _partir_en_chunks(texto_limpio)
    mode_label = "B (refinement)" if base_json is not None else "A (full extraction)"
    logger.info(
        "Groq API (%s, prompt_version=%s, mode=%s, total_chars=%d, chunks=%d)...",
        model_name,
        PROMPT_VERSION,
        mode_label,
        len(texto_limpio),
        len(chunks),
    )

    client = Groq()
    parciales: list[dict] = []

    for i, chunk in enumerate(chunks):
        logger.info("Procesando chunk %d/%d (%d chars)...", i + 1, len(chunks), len(chunk))
        user_message = _construir_user_message(chunk, base_json if i == 0 else None, allow_overwrite)
        raw_text = _llamar_llm(client, model_name, user_message)

        if trace_dir:
            _guardar_traza(trace_dir, f"05_llm_response_chunk{i+1}.txt", raw_text)

        try:
            parciales.append(_extraer_json(raw_text))
        except LLMParseError:
            logger.warning("Chunk %d falló el parseo JSON, se omite.", i + 1)

        if i < len(chunks) - 1:
            time.sleep(62)

    if not parciales:
        raise LLMParseError("Todos los chunks fallaron el parseo JSON.")

    plan_data = _mergear_resultados(parciales) if len(parciales) > 1 else parciales[0]

    if trace_dir:
        _guardar_traza(
            trace_dir,
            "06_llm_plandata.json",
            json.dumps(plan_data, ensure_ascii=False, indent=2),
        )

    check_estructura_minima(plan_data)

    return plan_data
